# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Habbit Builder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Habbit Builder
  pod 'DateScrollPicker'
  pod 'RealmSwift'
  pod 'SwipeCellKit'
  pod 'JTAppleCalendar'
  pod 'PopupDialog', '~> 1.1'

end
